---
name: "Update Casks"

on:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  homebrew-bump-cask:
    runs-on: macos-latest
    steps:
    - name: Update Homebrew cask
      uses: macauley/action-homebrew-bump-cask@v1
      with:
        token: ${{secrets.TOKEN}}
        tap: sharkusmanch/homebrew-cask
        livecheck: true

    - name: Enable automerge
      uses: daneden/enable-automerge-action@v1
      with:
        github-token: ${{secrets.TOKEN}}
        allowed-author: "sharkusmanch"
        merge-method: MERGE