---
name: "Update Casks"

on:
  workflow_dispatch:
  schedule:
    - cron: '20 */4 * * *'

jobs:
  homebrew-bump-cask:
    runs-on: macos-latest
    steps:
    - name: Update Homebrew cask
      uses: macauley/action-homebrew-bump-cask@v1
      with:
        token: ${{secrets.TOKEN}}
        tap: sharkusmanch/homebrew-cask
        livecheck: true