---
name: "Update Casks"

on:
  workflow_dispatch:

# on:
#   schedule:
#     - cron:  '30 5,17 * * *'

jobs:
  homebrew-bump-cask:
    runs-on: macos-latest
    steps:
    - name: Update Homebrew cask
      uses: macauley/action-homebrew-bump-cask@v1
      with:
        token: ${{secrets.TOKEN}}
        tap: sharkusmanch/homebrew-cask
        # Bump only these casks if outdated
        # cask: lime3ds, ludusavi
        livecheck: true

  automerge:
    name: Enable automerge
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: ${{secrets.TOKEN}}
          allowed-author: "sharkusmanch"
          merge-method: MERGE